### ISSUE TITLE
Creating new board with b key causes panic at Ubuntu 24.04 arm64 at M1 Air

### ISSUE THREAD

**Issue by xet7** [yashs662/rust_kanban#19]
**Describe the bug**
Creating new board with b key causes panic at Ubuntu 24.04 arm64 at M1 Air

**To Reproduce**

1. Install Asahi Ubuntu 24.04 arm64
2. `sudo apt -y install cargo`
3. `git clone  https://github.com/yashs662/rust_kanban` using newest commit https://github.com/yashs662/rust_kanban/commit/185fef827f42b11eeaca4116253f1a860c992b7c
3. `cargo run`

**Expected behavior**
Not panic

**Screenshots**
```
ubuntu@m1air:~/repos/rust_kanban$ RUST_BACKTRACE=1 cargo run

# Pressing at keyboard: b

thread 'main' panicked at src/ui/text_box.rs:983:26:
attempt to subtract with overflow
stack backtrace:
   0:     0xaaaac1b06b74 - std::backtrace_rs::backtrace::libunwind::trace::h7cc8868ad91e28f7
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0xaaaac1b06b74 - std::backtrace_rs::backtrace::trace_unsynchronized::hf51d4cbf741922e1
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xaaaac1b06b74 - std::sys_common::backtrace::_print_fmt::h2f8fac1780a554f9
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0xaaaac1b06b74 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfb881171b3e582c2
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0xaaaac1b437b8 - core::fmt::rt::Argument::fmt::hac58f985fe90592f
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/core/src/fmt/rt.rs:142:9
   5:     0xaaaac1b437b8 - core::fmt::write::h1fe2011c591e6e4e
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/core/src/fmt/mod.rs:1120:17
   6:     0xaaaac1aff300 - std::io::Write::write_fmt::hd7fcbca85742f117
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/io/mod.rs:1762:15
   7:     0xaaaac1b069a0 - std::sys_common::backtrace::_print::hb29597203a6ad3f6
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:47:5
   8:     0xaaaac1b069a0 - std::sys_common::backtrace::print::h6ef736028a02ed77
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:34:9
   9:     0xaaaac1b08b8c - std::panicking::default_hook::{{closure}}::h6b753200af39cdd2
  10:     0xaaaac1b087e4 - std::panicking::default_hook::h8ee1487419691390
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:292:9
  11:     0xaaaac111b968 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6d09e567445a978e
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/alloc/src/boxed.rs:2021:9
  12:     0xaaaac10e5ab4 - rust_kanban::main::{{closure}}::{{closure}}::hf53ac166dcca552e
                               at /home/ubuntu/repos/rust_kanban/src/main.rs:49:13
  13:     0xaaaac1b091a8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hde2103eaa9513e35
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/alloc/src/boxed.rs:2021:9
  14:     0xaaaac1b091a8 - std::panicking::rust_panic_with_hook::hf420639af1f4dd04
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:783:13
  15:     0xaaaac1b06f20 - std::panicking::begin_panic_handler::{{closure}}::heb97f3e0cb6f3ed3
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:649:13
  16:     0xaaaac1b06db4 - std::sys_common::backtrace::__rust_end_short_backtrace::hbfcbd48c856510f0
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:170:18
  17:     0xaaaac1b08d84 - rust_begin_unwind
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:645:5
  18:     0xaaaac1076d4c - core::panicking::panic_fmt::hc28d35037bc25df7
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/core/src/panicking.rs:72:14
  19:     0xaaaac1076dc0 - core::panicking::panic::h26b9ce13c5456a2d
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/core/src/panicking.rs:127:5
  20:     0xaaaac1135b30 - rust_kanban::ui::text_box::TextLineFormatter::line_number::h58f990e46aa4a2b3
                               at /home/ubuntu/repos/rust_kanban/src/ui/text_box.rs:983:26
  21:     0xaaaac11335d8 - rust_kanban::ui::text_box::TextBox::line_spans::he97e99c4f5b81884
                               at /home/ubuntu/repos/rust_kanban/src/ui/text_box.rs:457:13
  22:     0xaaaac1135154 - rust_kanban::ui::text_box::TextBoxRenderer::text::h9bbe8efbd0c7ffbd
                               at /home/ubuntu/repos/rust_kanban/src/ui/text_box.rs:905:28
  23:     0xaaaac113556c - <rust_kanban::ui::text_box::TextBoxRenderer as ratatui::widgets::Widget>::render::haf68cc4c991515e7
                               at /home/ubuntu/repos/rust_kanban/src/ui/text_box.rs:942:20
  24:     0xaaaac12e1c48 - ratatui::terminal::frame::Frame::render_widget::hada3bc86002b4b41
                               at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.26.3/src/terminal/frame.rs:75:9
  25:     0xaaaac1230dd0 - rust_kanban::ui::ui_helper::render_new_board_form::h54501719b2b41fb0
                               at /home/ubuntu/repos/rust_kanban/src/ui/ui_helper.rs:2364:5
  26:     0xaaaac12a1088 - rust_kanban::app::state::UiMode::render::h99271dbe31ea1de9
                               at /home/ubuntu/repos/rust_kanban/src/app/state.rs:340:17
  27:     0xaaaac12b32e4 - rust_kanban::ui::ui_main::draw::he1a7437001de69b7
                               at /home/ubuntu/repos/rust_kanban/src/ui/ui_main.rs:18:5
  28:     0xaaaac10fe388 - rust_kanban::util::start_ui::{{closure}}::{{closure}}::h5fad22061fbcdf9c
                               at /home/ubuntu/repos/rust_kanban/src/util.rs:49:30
  29:     0xaaaac1089244 - ratatui::terminal::terminal::Terminal<B>::draw::h891e606fa5e4333c
                               at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.26.3/src/terminal/terminal.rs:269:9
  30:     0xaaaac10fda3c - rust_kanban::util::start_ui::{{closure}}::h6838bab4a10d2fcf
                               at /home/ubuntu/repos/rust_kanban/src/util.rs:49:9
  31:     0xaaaac10e53b4 - rust_kanban::main::{{closure}}::h899245cc87ffd2e1
                               at /home/ubuntu/repos/rust_kanban/src/main.rs:117:32
  32:     0xaaaac10e330c - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::hde07445b38169612
                               at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:63
  33:     0xaaaac10e2d9c - tokio::runtime::coop::with_budget::h8cef2debe1726dde
                               at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
  34:     0xaaaac10e2d9c - tokio::runtime::coop::budget::hf0c46fb6a077a940
                               at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
  35:     0xaaaac10e2d9c - tokio::runtime::park::CachedParkThread::block_on::h33ff1f06d64fceb6
                               at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:31
  36:     0xaaaac10ea23c - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::h7ee1dac1b337ccc2
                               at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/blocking.rs:66:9
  37:     0xaaaac10ce544 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::h1bfbaffbc75fe8a9
                               at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  38:     0xaaaac10f7120 - tokio::runtime::context::runtime::enter_runtime::h25912ecb4595e135
                               at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
  39:     0xaaaac10ce4fc - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h6c112922092b1648
                               at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  40:     0xaaaac10776b8 - tokio::runtime::runtime::Runtime::block_on::h77353f5f4e239e70
                               at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/runtime.rs:349:45
  41:     0xaaaac1087040 - rust_kanban::main::ha7d5885b9d16e1d8
                               at /home/ubuntu/repos/rust_kanban/src/main.rs:119:5
  42:     0xaaaac108c5ec - core::ops::function::FnOnce::call_once::h4add372c0699ba28
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/core/src/ops/function.rs:250:5
  43:     0xaaaac111e03c - std::sys_common::backtrace::__rust_begin_short_backtrace::h1d804068e33b0db3
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/sys_common/backtrace.rs:154:18
  44:     0xaaaac1099f68 - std::rt::lang_start::{{closure}}::h6a32fd9fe0394385
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/rt.rs:167:18
  45:     0xaaaac1b08c28 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h30b447948ea89d93
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/core/src/ops/function.rs:284:13
  46:     0xaaaac1b08c28 - std::panicking::try::do_call::h13aaffc2bc1b3f68
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:552:40
  47:     0xaaaac1b08c28 - std::panicking::try::hcc5ac3d060ef034a
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:516:19
  48:     0xaaaac1b08c28 - std::panic::catch_unwind::h7880e72880358464
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panic.rs:142:14
  49:     0xaaaac1b08c28 - std::rt::lang_start_internal::{{closure}}::hacfdd7a9fc227add
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/rt.rs:148:48
  50:     0xaaaac1b08c28 - std::panicking::try::do_call::h87279a12e4c10bc8
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:552:40
  51:     0xaaaac1b08c28 - std::panicking::try::h5610a926e0319d2b
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panicking.rs:516:19
  52:     0xaaaac1b0b2a0 - std::panic::catch_unwind::h55eea13aefc1c64d
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/panic.rs:142:14
  53:     0xaaaac1b0b2a0 - std::rt::lang_start_internal::h10280ce03684d4c1
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/rt.rs:148:20
  54:     0xaaaac1099f38 - std::rt::lang_start::h74dc8cc65eaf3719
                               at /build/rustc-cssElz/rustc-1.75.0+dfsg0ubuntu1/library/std/src/rt.rs:166:17
  55:     0xaaaac10870dc - main
  56:     0xffffa27b84c4 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  57:     0xffffa27b8598 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  58:     0xaaaac10772b0 - _start
  59:                0x0 - <unknown>
```

**Desktop (please complete the following information):**
 - OS: Asahi Ubuntu  24.04 arm64 at M1 Air (dual boot Ubuntu/macOS)
 - Browser: Gnome Terminal, that comes with Ubuntu

**Comment by yashs662** [comment]
Hi, please use the release mode, as these overflows have been accounted for. I am not targeting dev mode to be stable as of yet as performance is not great in dev mode so it is difficult to work with. I have noted this and once the dev mode performance is good enough its behavior should match the release mode.
Please let me know if you are facing this issue with release mode as well

**Comment by xet7** [comment]
@yashs662 

Thanks! I built with release mode, and not it works.
```
cargo build --release
```
