### ISSUE TITLE
Crashes when adding character like Ö

### ISSUE THREAD

**Issue by xet7** [yashs662/rust_kanban#7]
**Describe the bug**
Crashes when adding character like Ö

**To Reproduce**
1. Try write board name starting with scandinavian character Ö. Maybe same would be with characters like ÖöÄäÅå.

**Expected behavior**
No crash

**Screenshots**
```
$ RUST_BACKTRACE=1 cargo run

thread 'main' panicked at 'assertion failed: self.is_char_boundary(idx)', /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/string.rs:1532:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
   3: alloc::string::String::insert
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/string.rs:1532:9
   4: rust_kanban::app::app_helper::handle_user_input_mode::{{closure}}
             at ./src/app/app_helper.rs:1971:25
   5: rust_kanban::app::App::do_action::{{closure}}
             at ./src/app/mod.rs:144:46
   6: rust_kanban::start_ui::{{closure}}
             at ./src/lib.rs:61:65
   7: rust_kanban::main::{{closure}}
             at ./src/main.rs:88:31
   8: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/wekan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/park.rs:283:63
   9: tokio::runtime::coop::with_budget
             at /Users/wekan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
  10: tokio::runtime::coop::budget
             at /Users/wekan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:73:5
  11: tokio::runtime::park::CachedParkThread::block_on
             at /Users/wekan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/park.rs:283:31
  12: tokio::runtime::context::BlockingRegionGuard::block_on
             at /Users/wekan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/context.rs:315:13
  13: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/wekan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/mod.rs:66:9
  14: tokio::runtime::runtime::Runtime::block_on
             at /Users/wekan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/runtime.rs:304:45
  15: rust_kanban::main
             at ./src/main.rs:90:5
  16: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.4 at M1 Air
 - Browser: macOS terminal

**Additional context**
Installed newest Rust stable today. Did git clone this repo and cargo run.

**Comment by xet7** [comment]
```
$ RUST_BACKTRACE=full cargo run

thread 'main' panicked at 'assertion failed: self.is_char_boundary(idx)', /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/string.rs:1532:9
stack backtrace:
   0:        0x10469a0f0 - std::backtrace_rs::backtrace::libunwind::trace::h0a647ce7e8dc2fab
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10469a0f0 - std::backtrace_rs::backtrace::trace_unsynchronized::hea920694a2a8ac80
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10469a0f0 - std::sys_common::backtrace::_print_fmt::h7b4e20c1da2ebb61
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x10469a0f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h819e9cbdf1a9e730
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x1046b5628 - core::fmt::write::ha5e9bf3131ecb7c0
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:        0x104696ed8 - std::io::Write::write_fmt::h414ce9994bf17404
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:        0x104699f04 - std::sys_common::backtrace::_print::h28d98f2094da6d1d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x104699f04 - std::sys_common::backtrace::print::h8072db0bbd5bcc3d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x10469b920 - std::panicking::default_hook::{{closure}}::h2c85c5b0c2ede151
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:        0x10469b6e0 - std::panicking::default_hook::hcf2f70992d02f6fe
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:        0x10414102c - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h7155be30122d6aab
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
  11:        0x104132d54 - rust_kanban::main::{{closure}}::{{closure}}::h4b7c99ab0f7fcfdd
                               at /Users/wekan/repos/rust_kanban/src/main.rs:41:13
  12:        0x10469bf34 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::he07e730a14cc7476
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
  13:        0x10469bf34 - std::panicking::rust_panic_with_hook::h023af7f90b47eb8b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
  14:        0x10469bcec - std::panicking::begin_panic_handler::{{closure}}::h14283519edc1d634
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:580:13
  15:        0x10469a510 - std::sys_common::backtrace::__rust_end_short_backtrace::hc366c0b0cef5b747
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  16:        0x10469bac0 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  17:        0x1046ce950 - core::panicking::panic_fmt::h324f50b29db90195
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  18:        0x1046ce9c0 - core::panicking::panic::h0335fbd7add43117
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
  19:        0x10413edd8 - alloc::string::String::insert::h4c65ac55861127f5
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/string.rs:1532:9
  20:        0x104109470 - rust_kanban::app::app_helper::handle_user_input_mode::{{closure}}::hcf947f02ec80eee7
                               at /Users/wekan/repos/rust_kanban/src/app/app_helper.rs:1971:25
  21:        0x104137714 - rust_kanban::app::App::do_action::{{closure}}::ha08130ae9bcde92e
                               at /Users/wekan/repos/rust_kanban/src/app/mod.rs:144:46
  22:        0x104129360 - rust_kanban::start_ui::{{closure}}::h8a78a35fc08be4ed
                               at /Users/wekan/repos/rust_kanban/src/lib.rs:61:65
  23:        0x1041328b8 - rust_kanban::main::{{closure}}::h2a8d886d0142269e
                               at /Users/wekan/repos/rust_kanban/src/main.rs:88:31
  24:        0x1040e7d10 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h5ef03ebd8b559776
                               at /Users/wekan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/park.rs:283:63
  25:        0x1040e7790 - tokio::runtime::coop::with_budget::h3bc3af85dea46d8e
                               at /Users/wekan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
  26:        0x1040e7790 - tokio::runtime::coop::budget::h90ca0f43b4a92b4c
                               at /Users/wekan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:73:5
  27:        0x1040e7790 - tokio::runtime::park::CachedParkThread::block_on::haf413d8646b22b43
                               at /Users/wekan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/park.rs:283:31
  28:        0x10411431c - tokio::runtime::context::BlockingRegionGuard::block_on::hec21553c962450e9
                               at /Users/wekan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/context.rs:315:13
  29:        0x1041410cc - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h5a9c6df32d1d63a2
                               at /Users/wekan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/mod.rs:66:9
  30:        0x10412b8c4 - tokio::runtime::runtime::Runtime::block_on::h2182d9a16a91af72
                               at /Users/wekan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/runtime.rs:304:45
  31:        0x10410d1d4 - rust_kanban::main::h50d086b6e7978887
                               at /Users/wekan/repos/rust_kanban/src/main.rs:90:5
  32:        0x1041163f0 - core::ops::function::FnOnce::call_once::h8c89b531b8d81780
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  33:        0x1040e6ee0 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdff637f092cb8a47
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:134:18
  34:        0x104135668 - std::rt::lang_start::{{closure}}::h310c784eba7c6f76
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:166:18
  35:        0x1046912f8 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6f7eb9f266759f90
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
  36:        0x1046912f8 - std::panicking::try::do_call::h54b2febb9ea02379
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  37:        0x1046912f8 - std::panicking::try::h95a2f9f45aeb75ea
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  38:        0x1046912f8 - std::panic::catch_unwind::h9686256fa0fc97a1
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  39:        0x1046912f8 - std::rt::lang_start_internal::{{closure}}::h227e8b10bc4e486b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
  40:        0x1046912f8 - std::panicking::try::do_call::h414d500a3ee5fa44
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  41:        0x1046912f8 - std::panicking::try::h4f025820961f1c3f
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  42:        0x1046912f8 - std::panic::catch_unwind::h0b71dfe3538d125d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  43:        0x1046912f8 - std::rt::lang_start_internal::h8ee16b8f6c950a26
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
  44:        0x104135634 - std::rt::lang_start::h217ff0c21a20b9fd
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:165:17
  45:        0x10410d264 - _main
´´´

**Comment by yashs662** [comment]
I am aware of this behaviour. I am in the process of revamping the text input behaviour to fix the cursor misalignment issues and special character insertion. Currently only English is supported. Bringing multilingual support soon✌🏻

**Comment by yashs662** [comment]
Please try the new release!! There are some cursor issues which will be fixed soon but characters should no longer crash the app

**Comment by xet7** [comment]
@yashs662 

Thanks! Now it works!
